### ISSUE TITLE
When using `wire.Set`s they are included in generated code and created a dependency on wire

### ISSUE THREAD

**Issue by pmalekn** [google/wire#153]
### Describe the bug

When using `wire.Set`s they are included in generated code and created a dependency on wire.

### To Reproduce

Write any injector that uses `wire.Set` (using `wire.NewSet()`) and observe that there is a dependency on wire in the generated code and binary built from generated sources (can be checked with e.g. `strings`).

## Expected behavior

There should be no dependency in the generated code nor in the binary build from generated sources.

### Version

[65ae46b7eaa146e99673e290251ea26f28139362](https://github.com/google/wire/commit/65ae46b7eaa146e99673e290251ea26f28139362)

**Comment by zombiezen** [comment]
@pmalekn, is this causing an issue other than having a dependency? The `wire` package intentionally has a small transitive closure of dependencies because provider sets necessarily need to call `wire.NewSet`, and we are very conscious to avoid including new dependencies to this package or otherwise increase code size here.

For context, prototype versions of Wire used comments to declare provider sets to avoid any dependency, but this didn't end well. See [this FAQ](https://github.com/google/wire/blob/master/docs/faq.md#why-use-pseudo-functions-to-create-provider-sets-or-injectors) for more details.

**Comment by pmalekn** [comment]
@zombiezen Ok, I believe I've read somewhere that using wire does not involve adding new dependencies but somehow I cannot find it now (obviously).

It's not a problem on its own - I understood from the docs that the outcoming of using a tool to generate code wouldn't have an impact on my dependencies, that's all.

I guess then that this can be closed then.

**Comment by zombiezen** [comment]
Sounds good. Let me know if you find where that claim is, so we can amend if necessary.

The injector itself does not require runtime support, but calls to the marker functions may be scattered outside the injector body. It's true that this non-zero cost, but it should be negligible and we aim to keep it negligible.
