### ISSUE TITLE
wire.ProviderSet is not a provider or a provider set

### ISSUE THREAD

**Issue by titpetric** [google/wire#226]
~~~go
//+build wireinject

package user

import (
        "context"

        "github.com/google/wire"
)

func New(ctx context.Context, wireSet wire.ProviderSet) (*Server, error) {
        wire.Build(
                wire.Struct(new(Server), "*"),
                wireSet,
        )
        return nil, nil
}
~~~

Results in an error like:

~~~
server/user/wire.go:14:3: var wireSet github.com/google/wire.ProviderSet is not a provider or a provider set
wire: error loading packages
~~~

I'm not sure what's wrong here. The wireSet provided is directly a result of calling wire.NewSet(providerFunc). How can I pass a ProviderSet to the injector?

**Comment by zombiezen** [comment]
Can you also include the code that declares and initializes `wireSet`?

**Comment by titpetric** [comment]
```go
getDB := func() (*sqlx.DB, error) {
        return sqlx.Connect(config.db.Driver, config.db.DSN)
}

inject := wire.NewSet(
        getDB,
)

srv, err := server.New(ctx, inject)
~~~

**Comment by zombiezen** [comment]
Thanks! Wire intentionally doesn't support passing in provider sets dynamically in the way that you're trying to use it. In order for Wire to generate code, it needs to know at code generation time how it's going to resolve the dependency graph. Taking in a provider set would require knowledge at runtime, which would make Wire significantly more complex. I'm going to close this issue out, because this isn't something we're going to support.

Tangentially related: you may want to track #69 for using function values as providers.

**Comment by titpetric** [comment]
So if I understand correctly, I can only pass a ProviderSet via context (e.g. package-level var?). I don't understand the restriction or more accurately, how I can provide a *sqlx.DB without having a function that provides an sqlx.DB? Within the scope instead of an argument?

**Comment by titpetric** [comment]
Aight, promoted the `getDB` into public package scope, and passed it directly into wire.Build. Thanks.
